### ISSUE TITLE
Merge latest trix features and fixes

### ISSUE THREAD

**Issue by aperkins81** [kylefox/trix#11]
https://github.com/basecamp/trix/releases

This still breaks for me in 5.2.1 with wrong number of arguments https://github.com/kylefox/trix/commit/a5febc816b097604ac0b844381057ad745cccc38

**Comment by kylefox** [comment]
[`trix-rails 2.0.0`](https://rubygems.org/gems/trix-rails/versions/2.0.0) has been published and includes Trix 1.0.0.

> This still breaks for me in 5.2.1 with wrong number of arguments

Hmm, I added an appraisal for 5.2.1 and [the specs pass](https://travis-ci.org/kylefox/trix/jobs/435050213). If you're still experiencing this problem, please open a new pull request with a spec/example that illustrates the issue and we can investigate further.
