### ISSUE TITLE
 how to extend the toolbar using this gem?

### ISSUE THREAD

**Issue by gujindv** [kylefox/trix#13]
hi, I'm trying to extend the toolbar with trix editor, like adding a image upload button.
Is it possible to customize when using your gem?

**Comment by kylefox** [comment]
To my knowledge Trix doesn't have an API for (easily) creating extensions/plugins 😕

Your best bet is to refer to the [Trix readme](https://github.com/basecamp/trix) to see if it's possible to implement your functionality using the existing APIs.

This gem doesn't do much except output the `<trix-editor>` tag — so you're able to do anything that'd you're able to do with Trix itself (for example, [observing Trix events](https://github.com/basecamp/trix#observing-editor-changes)).
