### ISSUE TITLE
Trix Toolbar undo/redo going off of screen for mobile

### ISSUE THREAD

**Issue by RailsCod3rFuture** [kylefox/trix#15]
I'm using Simple_Form's version of the trix editor input component. The issue I'm having is the trix editor is leaving the screen, even though its wrapped in a bootstrap container. Do you have a css class included in the package that addresses mobile views?

**Comment by kylefox** [comment]
`trix-rails` doesn't add any styles — all styles are from [Trix core](https://github.com/basecamp/trix).

It's possible that the Simple Form helper is rendering incorrectly. Do you see the same problem if you use the standard [`form.trix_editor` builder](https://github.com/kylefox/trix#form-builder)?

**Comment by RailsCod3rFuture** [comment]
Testing right now.

**Comment by RailsCod3rFuture** [comment]
Could be an issue with Rails 5.2 or Bootstrap 4. I'm using simple_form because it works extremely well with CountryStateSelect. I updated simple_form to 4.1
I tried rendering using <%= f.trix_editor :body, class: 'form-control %> and <%= f.input :body, as: :trix_editor %> Same results, with it leaving the container. I'll try again with the builder tomorrow & re-open if that fails as well.

**Comment by kylefox** [comment]
Interesting. Thanks for investigating so thoroughly. It may be a general issue with Bootstrap 4 and Trix itself.
