### ISSUE TITLE
Security Fix in 1.2.2 (sanitizing pasted HTML (#709)) 

### ISSUE THREAD

**Issue by smann297** [kylefox/trix#20]
Hi Kyle, 

Thanks for maintaining this gem. 

There is currently a security fix in version 1.2.2 

SECURITY: Fix sanitizing pasted HTML (#709)

https://github.com/basecamp/trix/releases

Would it be possible to bump the version of trix in this gem up to 1.2.2 ? 

@kylefox

**Comment by afomera** [comment]
Hi there @smann297 thanks for the issue, sorry it took so long to get to this.

We've just pushed and released v2.3.0 with Trix 1.3.1 which includes this security fix + additional ones.
