### ISSUE TITLE
Change to version numbers?

### ISSUE THREAD

**Issue by kylefox** [kylefox/trix#4]
The [original version of this gem](https://github.com/maclover7/trix) followed the same version numbers as [Trix itself](https://github.com/basecamp/trix).

The problem with this approach is that it makes it difficult to release new features and bug fixes independently of Trix. For example: if Trix and `trix-rails` are both at v.0.11.4, and a bug is then fixed in `trix-rails`, what happens to the version number?

I think the solution is to allow Trix and `trix-rails` version numbers to diverge. `trix-rails` would follow it's own [SemVer](https://semver.org/), and would also increment major/minor/patch versions alongside Trix.

Some examples:

### Patch

- Trix is at 0.11.4
- `trix-rails` is at 0.9.2
- Trix 0.11.5 is released (patch)
- `trix-rails` is bumped to 0.9.3 (patch)

### Minor

- Trix is at 0.11.4
- `trix-rails` is at 0.9.2
- Trix 0.12.0 is released (minor)
- `trix-rails` is bumped to 0.10.0 (patch)

Does this seem like a reasonable approach?

**Comment by Schwad** [comment]
Just my two cents here. I think this is a reasonable approach. We increment on our own improvements/changes and bump as well with main trix. Sounds good to me! :thumbsup:

**Comment by kylefox** [comment]
Ok, we're now officially decoupled from Trix's own versioning scheme 🙌

[`trix-rails 1.0.0`](https://rubygems.org/gems/trix-rails/versions/1.0.0) has been released, and a [changelog](https://github.com/kylefox/trix/blob/master/CHANGELOG.md) has been added.
