### ISSUE TITLE
Feature Request - Add href target to links?

### ISSUE THREAD

**Issue by ghost** [kylefox/trix#7]
This had been requested in the actual Trix basecamp package:

https://github.com/basecamp/trix/issues/286
https://github.com/basecamp/trix/issues/55

But I think the consensus is that the Trix developers won't support a change like this and many believe it to be a poor decision.

So my questions are:

1. Will this feature be helpful?
2. Is it possible for this change to be made here?
3. What is the effort / time estimations involved with that?

**Comment by kylefox** [comment]
Hi — this is just the repository for the Trix integration with Ruby on Rails. We aren't involved in the development of Trix itself, we simply bundle Trix to make it easy to include in Ruby on Rails apps.

For what it's worth, I've used [this script workaround](https://github.com/basecamp/trix/issues/55#issuecomment-238966508) in the past, and it's worked well. Good luck!
